upstream backend_pool {
    server backend-prod:3000;
    server backend-prod-2:3000;
}

server {
    listen 80;
    server_name localhost;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    root /usr/share/nginx/html;

    error_page 404 /errors/404.html;
    location = /errors/404.html {
        root /usr/share/nginx/html;
        internal;
    }


    location /api/ {
        limit_req zone=api_limit;
        proxy_pass http://backend_pool/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://frontend-prod:80;
        proxy_intercept_errors on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
