name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build Docker images
        run: docker compose build

      - name: Start services
        run: |
          docker network create devops-network
          docker compose up -d

      - name: Test API
        run: curl --fail 127.0.0.1:8080/api/
